#!/usr/bin/env python3

'''
Required packages -

python3
opencv (and python bindings)
numpy

'''

import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt

def make_gauss(centre, amp, sig, shapdim):

    '''just makes a Gaussian centred on chosen coordinates to
    use as the grav potential in the field'''

    sidelenx = shapdim[1]
    sideleny = shapdim[0]
    l = np.zeros(shapdim)

    for i in range(0, sideleny):

        for j in range(0, sidelenx):

            l[i, j] = np.sqrt((centre[0]-i)**2+(centre[1]-j)**2)

    gaussblob = amp*np.exp(-(l**2)/sig)
    return gaussblob


def tranform(image, grad, lenx, leny):

    imagel = image

    for i in range(0, lenx):

        for j in range(0, leny):

            imagel[i, j, 0] = image[(i-int(grad[0][i][j]) % frame.shape[0]), (j-int(grad[1][i][j]) % frame.shape[1]), 0]
            imagel[i, j, 1] = image[(i-int(grad[0][i][j]) % frame.shape[0]), (j-int(grad[1][i][j]) % frame.shape[1]), 1]
            imagel[i, j, 2] = image[(i-int(grad[0][i][j]) % frame.shape[0]), (j-int(grad[1][i][j]) % frame.shape[1]), 2]

    return imagel


if __name__ == "__main__":

    frame = cv.imread("Ben.jpg")

    rows, cols, ch = frame.shape
    gauss = make_gauss((rows/3, cols/1.8), 5000, 1000, (rows, cols))
    grad = np.gradient(gauss)

    result = tranform(frame, grad, rows, cols)
    cv.imwrite("BenLensed.jpg", result)
