#!/usr/bin/env python2

import numpy
import pygame
import pygame.camera


def grayscale(img):
    arr = pygame.surfarray.array3d(img)
    # luminosity filter
    avgs = [[(r*0.298 + g*0.587 + b*0.114) for (r, g, b) in col] for col in arr]
    arr = numpy.array([[[avg, avg, avg] for avg in col] for col in avgs])
    return pygame.surfarray.make_surface(arr)

pygame.camera.init()
cam = pygame.camera.Camera("/dev/video0", (640, 480))
cam.start()
img = cam.get_image()
pygame.image.save(img.convert_alpha(), "filename.jpg")
