#!/usr/bin/env python3

'''
Required packages -

python3
opencv (and python bindings)
numpy

'''
import lensface as lf
import cv2 as cv
import numpy as np
import argparse as ap
import os as os


def main(filename, gauss_loc, gauss_amp, gauss_sig):

    savename = os.path.splitext(filename)[0] + "Lensed" + os.path.splitext(filename)[1]

    frame = cv.imread(filename)
    rows, cols, ch = frame.shape

    gauss, rad = lf.make_gauss(gauss_loc, gauss_amp, gauss_sig, (rows, cols))
    grad = np.gradient(gauss)

    transpos = lf.calc_tranform(grad, rows, cols)

    result = frame[transpos]
    lensim = np.reshape(result, frame.shape) # Reshape back to 2D array

    cv.circle(lensim, (int(gauss_loc[1]*cols), int(gauss_loc[0]*rows)), rad, 0, -1)

    cv.imwrite(savename, lensim)


if __name__ == "__main__":

    parser = ap.ArgumentParser(description="Arguments")

    parser.add_argument("-p", "--path", help="Path to Image File", required=True, type=str)
    parser.add_argument("-a", "--amp", help="Amplitude of Gaussian", required=False, type=float)
    parser.add_argument("-s", "--sig", help="Sigma of Gaussian", required=False, type=float)

    args = parser.parse_args()

    loc = (0.5, 0.5)
    amp = 1e4
    sig = 1e3

    if (args.amp != None) :
        amp = int(args.amp)

    if (args.sig != None) :
        sig = int(args.sig)

    main(args.path, loc, amp, sig)
