#!/usr/bin/env python3

'''
Required packages -

python3
opencv (and python bindings)
numpy

'''

import cv2 as cv
import numpy as np

video_capture = cv.VideoCapture(0)  # 0 - Default camera

while True:
    # Capture frame-by-frame
    ret, frame = video_capture.read()

    rows, cols, ch = frame.shape

    # Example tranformation - can do any sort of matrix transform here

    pts1 = np.float32([[cols/3.0, 65], [cols, rows/1.5], [28, rows], [cols, rows]])
    pts2 = np.float32([[0, 0], [cols, 0], [0, rows], [cols, rows]])

    M = cv.getPerspectiveTransform(pts1, pts2)

    dst = cv.warpPerspective(frame, M, (cols, rows))

    # Display the resulting frame
    cv.imshow('Video', dst)

    if cv.waitKey(1) & 0xFF == ord('q'):
        break

# When everything is done, release the capture
video_capture.release()
cv.destroyAllWindows()
